name: Go

on:
  push:
    branches: [ "main" ]
    tags: "*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      run: go build -v
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: 
        GHR_PATH: birdweather_daily_email
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
